version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    build:
      context: .
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOST
    working_dir: /usr/src/api
    volumes:
      - ./:/usr/src/api
      - ./logs:/var/log/elios/
      - packages:/usr/local/lib/python3.7/site-packages/
    ports:
      - "3000:3000"
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  packages:
