services:
  api:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - ${PUBLIC_API_PORT}:8000
      - ${PUBLIC_DEBUG_BINDING}:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app/
      - venv:/app/.venv


  db:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${PUBLIC_POSTGRES_PORT}:${POSTGRES_PORT:-5432}
    volumes:
      # Persist database state between docker sessions/builds
      - db_volume:/var/lib/postgresql/data


volumes:
  db_volume:
  venv:


