# Generated by Django 3.1.2 on 2020-10-31 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201030_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='list_section',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='symbol',
        ),
        migrations.AddField(
            model_name='listsection',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.list'),
        ),
        migrations.AlterField(
            model_name='guser',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.household'),
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.measurement')),
            ],
        ),
    ]
