# Generated by Django 3.1.2 on 2020-10-31 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201031_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listsection',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list'),
        ),
    ]
