# Generated by Django 3.1.2 on 2020-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201031_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='referenceable',
            field=models.BooleanField(default=True),
        ),
    ]
