# Generated by Django 3.1.2 on 2021-04-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_list_referenceable'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='form',
            field=models.IntegerField(choices=[(0, 'Volume'), (1, 'Weight'), (2, 'Temperature')], default=2),
            preserve_default=False,
        ),
    ]
