# Generated by Django 3.1.2 on 2021-04-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_measurement_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.measurementfamily'),
        ),
    ]
