# Generated by Django 4.0.4 on 2023-01-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_recipe_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
