# Generated by Django 4.0.4 on 2023-01-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_recipe_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.household')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('purchasing_quantity', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.household')),
                ('purchasing_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.measurement')),
                ('tags', models.ManyToManyField(to='api.tag')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
