# Generated by Django 4.0.4 on 2023-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tag_ingredient_item_ingredient_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'managed': True, 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
