# Generated by Django 4.0.4 on 2023-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_list_tags_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='on_type',
            field=models.CharField(default='Ingredient', max_length=50),
            preserve_default=False,
        ),
    ]
