# Generated by Django 4.0.4 on 2023-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tag_on_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
