# Generated by Django 4.0.4 on 2023-03-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_item_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='purchasing_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
