#!/usr/bin/env bash
set +e

DIR="$(dirname $(realpath $0))"
CURRENT="$(python $DIR/jq.py '_meta.hash.sha256' < Pipfile.lock)";
CACHE_FILE="$VIRTUAL_ENV/.pipfile-hash"
CACHE="$(cat $CACHE_FILE 2>/dev/null)"

set -e


if [[ -z "$CURRENT" || "$CURRENT" != "$CACHE" ]]; then
    # python virtual enviornment
    if [[ ! $(which python) == *"$VIRTUAL_ENV"* ]]; then
        1>&2 echo -e "\033[33;1mCreating virtual environment...\033[0m";
        python3 -m virtualenv --python=$(which python3) $VIRTUAL_ENV;
        . $VIRTUAL_ENV/bin/activate;

        pip install --upgrade pip wheel pipenv
    fi

    # python packages
    1>&2 echo -e "\033[33;1mInstalling requirements...\033[0m";
    pipenv sync --dev

    echo "$CURRENT" > $CACHE_FILE;
fi
